version: "3.8"

services:
  web01:
    image: cedrick13bienvenue/currency-converter-cli:v1
    container_name: web01
    ports:
      - "8080:8080"
    environment:
      - EXCHANGE_API_KEY=${EXCHANGE_API_KEY}
      - NODE_ENV=production
      - PORT=8080
    restart: unless-stopped
    networks:
      - currency-net
    # Volume for logs (optional)
    volumes:
      - ./logs:/app/logs:rw
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
        reservations:
          memory: 128M
          cpus: "0.25"

  web02:
    image: cedrick13bienvenue/currency-converter-cli:v1.1
    container_name: web02
    ports:
      - "8081:8080"
    environment:
      - EXCHANGE_API_KEY=${EXCHANGE_API_KEY}
      - NODE_ENV=production
      - PORT=8080
    restart: unless-stopped
    networks:
      - currency-net
    # Volume for logs (optional)
    volumes:
      - ./logs:/app/logs:rw
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
        reservations:
          memory: 128M
          cpus: "0.25"

  lb-01:
    image: haproxy:alpine
    container_name: lb-01
    ports:
      - "80:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - web01
      - web02
    networks:
      - currency-net
    restart: unless-stopped

networks:
  currency-net:
    driver: bridge
    name: currency-converter-network

# Volumes for persistent data (if needed in future)
volumes:
  logs:
    driver: local
